export enum ParticipantType {
  LINER = 'LINER',
  TELEMARKETING_SUPERVISOR = 'TELEMARKETING_SUPERVISOR',
  TELEMARKETING_CONFIRMER = 'TELEMARKETING_CONFIRMER',
  TELEMARKETER = 'TELEMARKETER',
  FIELD_MANAGER = 'FIELD_MANAGER',
  FIELD_SUPERVISOR = 'FIELD_SUPERVISOR',
  FIELD_SELLER = 'FIELD_SELLER',
  SALES_MANAGER = 'SALES_MANAGER',
  SALES_GENERAL_MANAGER = 'SALES_GENERAL_MANAGER',
  POST_SALE = 'POST_SALE',
  CLOSER = 'CLOSER',
}
