import { SystemHelp } from '../interfaces/context.interface';

export const systemHelpData: SystemHelp = {
  quickHelp: {
    SYS: [
      '¿Cómo crear un nuevo usuario?',
      '¿Cómo crear un proyecto con Excel?',
      '¿Dónde descargar la plantilla Excel?',
      '¿Cómo validar archivo de proyecto?',
      '¿Cómo listar y filtrar usuarios?',
      '¿Cómo actualizar un usuario?',
      '¿Cómo ver detalle de proyecto?',
      '¿Cómo editar lotes y etapas?',
    ],
    ADM: [],
    REC: [],
    VEN: [],
    JVE: [],
    COB: [],
    DEFAULT: [],
  },
  stepByStepGuides: {
    createUser: {
      title: 'Crear un nuevo usuario',
      applicableRoles: ['SYS'],
      steps: [
        '👥 Ve al menú "Usuarios" en el sistema',
        '➕ Haz click en "+ Nuevo Usuario" para abrir el formulario',
        '📝 Completa los campos requeridos:',
        '   • Nombre del usuario',
        '   • Apellido del usuario',
        '   • Documento de Identidad',
        '   • Email (debe ser único)',
        '   • Rol (selecciona de la lista desplegable)',
        '   • Contraseña (mínimo 6 caracteres)',
        '💾 Haz click en "Crear Usuario" para guardar',
        '✅ Verifica que aparezca el mensaje de confirmación',
        '📧 Opcionalmente, envía las credenciales al nuevo usuario',
      ],
    },
    listUsers: {
      title: 'Listar y filtrar usuarios',
      applicableRoles: ['SYS'],
      steps: [
        '👥 Ve al menú "Usuarios" en el sistema',
        '📋 Se mostrará automáticamente la lista de usuarios',
        '🔍 Para filtrar usuarios puedes usar:',
        '   • Campo de búsqueda por nombre o email',
        '   • Filtro por estado (activo/inactivo)',
        '📊 La lista muestra: nombre, email, rol, estado y fecha de creación',
        '✏️ Usa el botón "Editar" para modificar cualquier usuario',
      ],
    },
    updateUser: {
      title: 'Actualizar información de usuario',
      applicableRoles: ['SYS'],
      steps: [
        '👥 Ve al menú "Usuarios" en el sistema',
        '🔍 Busca el usuario por nombre o email en la lista',
        '✏️ Haz click en "Editar" del usuario deseado',
        '📝 Se abrirá el formulario con los datos actuales:',
        '   • Nombre (editable)',
        '   • Apellido (editable)',
        '   • Documento de Identidad (editable)',
        '   • Email (editable)',
        '   • Rol (seleccionable de lista)',
        '   • Contraseña (opcional, dejar vacío si no cambias)',
        '   • Estado (activo/inactivo)',
        '💾 Haz click en "Guardar Cambios"',
        '✅ Verifica que aparezca el mensaje de confirmación',
      ],
    },
    createProjectExcel: {
      title: 'Crear proyecto mediante archivo Excel',
      applicableRoles: ['SYS'],
      steps: [
        '🏘️ Ve al menú "Gestión de Proyectos"',
        '➕ Selecciona "Nuevo Proyecto" del submenú',
        '📊 PASO 1: Carga del archivo Excel',
        '   • Descarga la plantilla Excel si no la tienes',
        '   • Completa la plantilla con los datos del proyecto',
        '   • Sube el archivo usando el botón "Cargar archivo"',
        '   • Haz click en "Validar archivo"',
        '🔍 PASO 2: Revisar Datos',
        '   • Revisa el resumen del proyecto mostrado',
        '   • Verifica: nombre, cantidad de lotes, valor total',
        '   • Revisa la tabla de lotes (etapa, manzana, lote, área, precios)',
        '   • Si hay errores, corrige el archivo y vuelve al paso 1',
        '   • Si todo está correcto, haz click en "Crear Proyecto"',
        '✅ PASO 3: Finalizar',
        '   • Verifica el mensaje de confirmación',
        '   • Serás redirigido a la lista de proyectos',
        '   • El proyecto aparecerá en la lista con estado "activo"',
      ],
    },
    listProjects: {
      title: 'Listar y gestionar proyectos',
      applicableRoles: ['SYS'],
      steps: [
        '🏘️ Ve al menú "Gestión de Proyectos"',
        '📋 Selecciona "Proyectos" del submenú',
        '📊 Se mostrará la lista con la siguiente información:',
        '   • Nombre del Proyecto',
        '   • Moneda (USD/PEN)',
        '   • Cantidad de Etapas',
        '   • Cantidad de Manzanas',
        '   • Lotes Activos',
        '   • Estado (activo/inactivo)',
        '   • Fecha de Creación',
        '🔍 Puedes filtrar por:',
        '   • Nombre del proyecto',
        '   • Estado del proyecto',
        '   • Ordenar por fecha de creación',
        '👀 Haz click en cualquier proyecto para ver su detalle',
      ],
    },
    projectDetail: {
      title: 'Ver y editar detalle de proyecto',
      applicableRoles: ['SYS'],
      steps: [
        '🏘️ Ve al menú "Gestión de Proyectos" → "Proyectos"',
        '👆 Haz click en el proyecto que deseas ver',
        '📊 Se mostrará el detalle completo:',
        '   • Información general del proyecto',
        '   • Tabla completa de lotes con todos los campos',
        '   • Estado de cada lote (disponible/reservado/vendido)',
        '⚙️ Opciones de edición disponibles:',
        '   • "Editar Proyecto" - Modifica info general',
        '   • "Editar Etapa" - Modifica etapas existentes',
        '   • "Editar Manzana" - Modifica manzanas existentes',
        '   • "Editar Lote" - Modifica lotes individuales',
        '➕ Opciones para agregar:',
        '   • "Agregar Etapa" - Nueva etapa al proyecto',
        '   • "Agregar Manzana" - Nueva manzana a una etapa',
        '   • "Agregar Lote" - Nuevo lote a una manzana',
        '💾 Recuerda guardar cambios después de cada edición',
      ],
    },
    downloadExcelTemplate: {
      title: 'Descargar plantilla Excel para proyectos',
      applicableRoles: ['SYS'],
      steps: [
        '🏘️ Ve al menú "Gestión de Proyectos"',
        '➕ Selecciona "Nuevo Proyecto"',
        '📊 En el Paso 1: Carga del proyecto',
        '⬇️ Haz click en "Descargar plantilla Excel"',
        '💾 Guarda el archivo en tu computadora',
        '📝 Abre el archivo y completa:',
        '   • Fila 1: Nombre del proyecto',
        '   • Fila 2: Moneda (USD o PEN)',
        '   • Fila 3 en adelante: Datos de lotes',
        '📋 Campos de lotes requeridos:',
        '   • Etapa, Manzana, Lote, Área (m²)',
        '   • Precio Lote, Precio HU, Estado',
        '⚠️ Importante: No modificar los encabezados de la plantilla',
      ],
    },
    validateProjectFile: {
      title: 'Validar archivo de proyecto',
      applicableRoles: ['SYS'],
      steps: [
        '📊 Una vez cargado el archivo Excel',
        '🔍 Haz click en "Validar archivo"',
        '⏳ El sistema procesará y validará:',
        '   • Formato correcto del archivo',
        '   • Campos obligatorios completos',
        '   • Datos válidos (precios, áreas, etc.)',
        '   • No duplicados en lotes',
        '✅ Si la validación es exitosa:',
        '   • Verás un resumen del proyecto',
        '   • Podrás proceder al Paso 2',
        '❌ Si hay errores:',
        '   • Se mostrará lista detallada de errores',
        '   • Indica fila y columna del problema',
        '   • Corrige el archivo y vuelve a validar',
        '💡 Tip: Revisa especialmente precios y áreas que sean números válidos',
      ],
    },
  },
  troubleshooting: {
    commonIssues: [
      {
        issue: 'No puedo acceder al sistema',
        solutions: [
          '🔐 Verificar credenciales de acceso correctas',
          '✅ Confirmar que el usuario esté activo en el sistema',
          '👑 Contactar al administrador del sistema',
          '🌐 Verificar conexión a internet estable',
          '🔄 Limpiar caché del navegador',
        ],
      },
      {
        issue: 'No veo todas las opciones del menú',
        solutions: [
          '🔒 Verificar permisos del rol asignado',
          '👑 Contactar al administrador para revisar permisos',
          '🔄 Cerrar sesión y volver a iniciar',
          '🧹 Limpiar caché del navegador',
          '🔍 Verificar que el rol tenga acceso a esa funcionalidad',
        ],
      },
      {
        issue: 'Error al guardar información',
        solutions: [
          '📝 Verificar que todos los campos obligatorios estén completos',
          '✅ Revisar formato de datos (email, teléfono, etc.)',
          '⏳ Intentar nuevamente en unos minutos',
          '🆘 Contactar soporte técnico si el problema persiste',
          '🔍 Verificar que no haya duplicados (email, documento)',
        ],
      },
      {
        issue: 'Error al validar archivo Excel de proyecto',
        solutions: [
          '📊 Verificar que uses la plantilla oficial descargada',
          '📋 No modificar los encabezados de la plantilla',
          '🔢 Verificar que precios y áreas sean números válidos',
          '🚫 Revisar que no haya lotes duplicados',
          '💰 Confirmar que la moneda sea USD o PEN',
          '📝 Verificar que todos los campos obligatorios estén completos',
          '⬇️ Descargar nueva plantilla si persiste el error',
        ],
      },
      {
        issue: 'No puedo crear un nuevo usuario',
        solutions: [
          '📧 Verificar que el email no esté ya registrado',
          '🆔 Confirmar que el documento sea único',
          '🔒 Verificar que la contraseña cumpla los requisitos mínimos',
          '👑 Confirmar que tienes permisos de administrador',
          '📝 Completar todos los campos obligatorios',
          '🔄 Actualizar la página e intentar nuevamente',
        ],
      },
      {
        issue: 'El proyecto no se crea después de validar el Excel',
        solutions: [
          '⏳ Esperar a que termine el proceso (puede tomar varios minutos)',
          '🔄 Verificar conexión a internet durante el proceso',
          '📊 Confirmar que el archivo no tenga errores ocultos',
          '💾 Intentar con un archivo Excel más pequeño para probar',
          '🆘 Contactar soporte si el problema persiste',
          '📋 Revisar los logs del sistema para detalles del error',
        ],
      },
    ],
  },
};
