export enum SunatTransaction {
  VENTA_INTERNA = 1,
  EXPORTACION = 2,
  VENTA_INTERNA_ANTICIPOS = 4,
  VENTAS_NO_DOMICILIADOS = 29,
  OPERACION_DETRACCION = 30,
  DETRACCION_RECURSOS_HIDROBIOLOGICOS = 31,
  DETRACCION_TRANSPORTE_PASAJEROS = 32,
  DETRACCION_TRANSPORTE_CARGA = 33,
  OPERACION_PERCEPCION = 34,
  VENTA_TURISTAS_TAX_FREE = 35,
}
